# -*- coding: utf-8 -*-
"""conll_tagged_ne.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ratmcu/wiki_ner/blob/master/conll_tagged_ne.ipynb
"""

!pip install wget
import os
import wget
try:
    import colabimport
except:
    colabimporturl = 'https://github.com/ratmcu/colaboratory_import/raw/master/colabimport.py'
    filename = colabimporturl.split("/")[-1].split("?")[0]
    if os.path.isfile(filename):
        os.remove(filename)
    wget.download(colabimporturl)
    import colabimport
colabimport.get_notebook('https://github.com/ratmcu/wiki_ner/blob/master/reusable_annotator.ipynb?raw=true')
colabimport.get_notebook('https://github.com/ratmcu/wiki_ner/blob/master/info_box.ipynb?raw=true')
# import io, os, sys, types
from reusable_annotator import PageContents
from info_box import InfoCard, PrivateEntities
import logging
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
# logging.debug("test")
class HashableTupleAnnotations(tuple):
    def __hash__(self):
        return hash(tuple(sorted([self[0:1],self[1:2]])))
!pip install spacy
!python -m spacy download en_core_web_sm
import spacy
# from spacy import displacy
from collections import Counter
nlp = spacy.load("en_core_web_sm")
import re
!pip install pyahocorasick
!pip install fuzzyset
from ahocorasick import Automaton
import fuzzyset
from operator import itemgetter, attrgetter
import pandas as pd
# import json

class WikiConLLTagger():
    def __init__(self, url):
        self.url = url
        self.page = PageContents(url)
        self.info_card = InfoCard(self.page)
#         print(sorted(self.tag_factory.get_annotations(), key=lambda annot: annot[1][0]))

    def _get_annotations(self):
        '''stack all the annotations'''
        return sorted(sorted(self.tag_factory.get_annotations(), key=lambda annot: annot[1][0]), reverse=True) # sort them by the start index of the annotaion token

#     def get_metadata(self):
#         pe = self.private_entities
#         # pe = [list(map(lambda li: item[1], item)) for item in pe.items()]
#         dp = dict()
#         [dp.update({item[0]: item[1][1]}) for item in pe.items()]
#         dp.update({'URL' : self.url})
#         return dp

    def place_tags(self):
        nlp = spacy.load("en_core_web_sm")
        self.text = self.page.get_text_chunk()
        self.private_entities = PrivateEntities(self.info_card).entity_dict
        self.doc = nlp(self.text)
#         self.spacy_noun_chunks =  [(chunk.text, chunk.start, chunk.end) for chunk in self.doc.noun_chunks]
        self.tag_factory = TagFactory(self)
        annotations = self._get_annotations()
        words = []
        tags = []
        annotation_tags = ['O']*len(self.doc)
#         annotation = annotations.pop()
        for annotation in annotations:
            annotation_tags[annotation[1][0]] = 'B-'+annotation[0] #
            for i in range(annotation[1][1]-annotation[1][0]-1):
                annotation_tags[annotation[1][0]+i+1] = 'I-'+annotation[0]
#         for token in self.doc:
#             words.append(token)
#             if token
        for sentence in self.doc.sents:
            tags.extend(annotation_tags[sentence.start:sentence.end])
            tags.append('\n')
            for token in sentence:
                words.append(token.text)
            words.append('\n')
#         print(words)
#         print(tags)
        return {'words': words, 'tags':tags}

class TagFactory():
    '''will keep a set of all the tagged annotations in the form of
       ('word phrase', 'ENTITY', start, end), each tagging function will update the list'''
    def __init__(self, tagger):
        self.doc =tagger.doc
        self.entity_dict = tagger.private_entities
        self.tag_set = set()
        self.neg_tag_set = set()
        self.spacy_noun_chunks =  [(chunk.text, chunk.start, chunk.end) for chunk in self.doc.noun_chunks]
        tagging_methods = [getattr(self, method) for method in dir(self) if callable(getattr(self, method)) and re.match('_tag_.*', method)]
        for method in tagging_methods:
            method()

    def get_tag_summary(self):
        BD_tags = len([y for y in self.tag_set if y[1]=='BD'])
        NBD_tags = len([y for y in self.neg_tag_set if y[1]=='NBD'])
#         [print(y) for y in self.neg_tag_set if y[1]=='NBD']
        CH_tags = len([y for y in self.tag_set if y[1]=='CH'])
        PR_tags = len([y for y in self.tag_set if y[1]=='PR'])
        SP_tags = len([y for y in self.tag_set if y[1]=='SP'])
        NPE_tags = len([y for y in self.neg_tag_set if y[1]=='NPE'])

        BP_tags = len([y for y in self.tag_set if y[1]=='BP'])
        NGPE_tags = len([y for y in self.neg_tag_set if y[1]=='NGPE'])

        ED_tags = len([y for y in self.tag_set if y[1]=='ED'])
        NORG_tags = len([y for y in self.neg_tag_set if y[1]=='NORG'])
        return {'BD': BD_tags,
                'NBD': NBD_tags,
                'CH': CH_tags,
                'PR': PR_tags,
                'SP': SP_tags,
                'NPE': NPE_tags,
                'BP': BP_tags,
                'NGPE': NGPE_tags,
                'ED': ED_tags,
                'NORG': NORG_tags,
                'SENTS': len([sent for sent in self.doc.sents])}

    def get_annotations(self):
        '''list with ('ENTITY', start, end) '''
        return [annot[1:] for annot in list(self.tag_set)]

    def _tag_bd(self):
        logging.debug('------BIRTHDAY MATCHING------')
        date_entities = []
        if not 'BIRTH_DATE' in self.entity_dict:
            return
        birth_dates =  [entity  for entity_list in self.entity_dict['BIRTH_DATE'] for entity in entity_list['entity_list']] #[{'dict_key':'Children', 'type':'PERSON', 'entity_list':[]}]
        for entity in self.doc.ents:
            if entity.label_ == 'DATE':
                date_entities.append((entity.text, entity.label_, entity.start, entity.end))

        for date in date_entities:
            fz = fuzzyset.FuzzySet(use_levenshtein=False)
            for word in date[0].split(): # add all the words into a fuzzy set from the entity
                fz.add(word)
            for j, detail in enumerate(birth_dates): # get a detail in the list under an info line
                matched_list = []
                tokens_in_detail = len(detail.split()) # split the detail into words
                for word in detail.split(): # get a word from the detail
                    result = fz.get(word)    # get the matching
                    if(result and result[0][0]>=0.5 and not len(result[0][1])/2 < len(word)/2): #if the matching confidence is high and word length is high
                        matched_list.append((word, result))
                if abs(len(matched_list) - tokens_in_detail) < 1 and len(matched_list)!=0:
                    annot = (date[0], 'BD', date[2:]) # exact phrase, entity tag, token indices
                    self.tag_set.add(HashableTupleAnnotations(annot))
                else:
                    annot = (date[0], 'NBD', date[2:]) # exact phrase, entity tag, token indices
                    self.neg_tag_set.add(HashableTupleAnnotations(annot))

    def _tag_bp(self):
        logging.debug('------BIRTH PLACES------')
        place_entities = []
        if not 'BIRTH_PLACE' in self.entity_dict:
            return
        birth_places = [entity  for entity_list in self.entity_dict['BIRTH_PLACE'] for entity in entity_list['entity_list']]
        for entity in self.doc.ents:
            if entity.label_ == 'GPE':
                place_entities.append((entity.text, entity.label_, entity.start, entity.end))
        for place in place_entities:
            fz = fuzzyset.FuzzySet(use_levenshtein=False)
            for word in place[0].split(): # add all the words into a fuzzy set from that sentence
                fz.add(word)
            for j, detail in enumerate(birth_places): # get a detail in the list under an info line
                matched_list = []
                tokens_in_detail = len(detail.split()) # split the detail into words
                for word in detail.split(): # get a word from the detail
                    result = fz.get(word)    # get the matching
                    if(result and result[0][0]==0.6):
                        matched_list.append((word, result))
                if abs(len(matched_list) - tokens_in_detail) < 1 and len(matched_list)!=0:
                    annot = (place[0], 'BP', place[2:])
                    logging.debug(annot)
                    self.tag_set.add(HashableTupleAnnotations(annot))
                else:
                    annot = (place[0], 'NGPE', place[2:]) # exact phrase, entity tag, token indices
                    self.neg_tag_set.add(HashableTupleAnnotations(annot))

        logging.debug('------NOUN CHUNCK MATCHING FOR BP------')
        for noun in self.spacy_noun_chunks:    #('Joachim Wilhelm Gauck', 0, 4)
            fz = fuzzyset.FuzzySet(use_levenshtein=False)
            for word in noun[0].split(): # add all the words into a fuzzy set from that sentence
                fz.add(word)
            for j, detail in enumerate(birth_places): # get a detail in the list under an info line
                matched_list = []
                tokens_in_detail = len(detail.split()) # split the detail into words
                for word in detail.split(): # get a word from the detail
                    result = fz.get(word)    # get the matching
                    if(result and result[0][0]==0.6):
                        matched_list.append((word, result))
                if abs(len(matched_list) - tokens_in_detail) < 1 and len(matched_list)!=0:
                    logging.debug((noun[0], 'BP', noun[1:]))
                    self.tag_set.add(HashableTupleAnnotations((noun[0], 'BP', noun[1:])))
#                 else:
#                     self.neg_tag_set.add(HashableTupleAnnotations((noun[0], 'NBP', noun[1:])))
    def _tag_spouse(self):
        logging.debug('------SPOUSES NAMES------')
        spouse_entities = []
        if not 'SPOUSES' in self.entity_dict:
            return
        spouse_names = [entity  for entity_list in self.entity_dict['SPOUSES'] for entity in entity_list['entity_list']]
        for entity in self.doc.ents:
            if entity.label_ == 'PERSON':
                spouse_entities.append((entity.text, entity.label_, entity.start, entity.end))

        for spouse in spouse_entities:
            fz = fuzzyset.FuzzySet(use_levenshtein=False)
            # for word in spouse[0].split(): # add all the words into a fuzzy set from the entity
            #     fz.add(word)
            fz.add(spouse[0])
            for j, detail in enumerate(spouse_names): # get a detail in the list under an info line(things coming from the side info box)
                # matched_list = []
                # tokens_in_detail = len(detail.split()) # split the detail into words
                # for word in detail.split(): # get a word from the detail
                #     result = fz.get(word)    # get the matching
                #     if(result and result[0][0]>=0.5 and not len(result[0][1])/2 < len(word)/2): #if the matching confidence is high and word length is high
                #         matched_list.append((word, result))
                result = fz.get(detail.split()[0])    # for a name, it should match the first name
                if(result and result[0][0]>=0.5 and not len(result[0][1])/2 < len(spouse[0])/2): #if the matching confidence is high and word length is high
                    annot = (spouse[0], 'SP', spouse[2:])
                    logging.debug(annot)
                    self.tag_set.add(HashableTupleAnnotations(annot))
                else:
                    annot = (spouse[0], 'NPE', spouse[2:]) # exact phrase, entity tag, token indices
                    self.neg_tag_set.add(HashableTupleAnnotations(annot))
        logging.debug('------NOUN CHUNCK MATCHING FOR SPOUSES------')
        for noun in self.spacy_noun_chunks:    #('Joachim Wilhelm Gauck', 0, 4)
            fz = fuzzyset.FuzzySet(use_levenshtein=False)
            for word in noun[0].split(): # add all the words into a fuzzy set from that sentence
                fz.add(word)
            for j, detail in enumerate(spouse_names): # get a detail in the list under an info line
                matched_list = []
                # tokens_in_detail = len(detail.split()) # split the detail into words
                for wn, word in enumerate(detail.split()): # get a word from the detail
                    result = fz.get(word)    # get the matching
                    if result and result[0][0]>=0.5 and not len(result[0][1])/2 < len(word)/2: #if the matching confidence is high and word length is high
                        matched_list.append((word, result))
                    elif wn == 0: #if the first word doesn't match, break the matching
                        break
                if  len(matched_list)!=0:
                    logging.debug((noun[0], 'SP', noun[1:]))
                    self.tag_set.add(HashableTupleAnnotations((noun[0], 'SP', noun[1:])))
#                 else:
#                     self.neg_tag_set.add(HashableTupleAnnotations((noun[0], 'NSP', noun[1:])))

    def _tag_edu(self):
        logging.debug('------EDUCATION INSTITUTIONS------')
        edu_entities = []
        if not 'EDUCATION' in self.entity_dict:
            return
        edu_names = [entity  for entity_list in self.entity_dict['EDUCATION'] for entity in entity_list['entity_list']]
        for entity in self.doc.ents:
            if entity.label_ == 'ORG':
                edu_entities.append((entity.text, entity.label_, entity.start, entity.end))

        for edu in edu_entities:
            fz = fuzzyset.FuzzySet(use_levenshtein=False)
            for word in edu[0].split(): # add all the words into a fuzzy set from that sentence
                fz.add(word)
            for j, detail in enumerate(edu_names): # get a detail in the list under an info line
                matched_list = []
                tokens_in_detail = len(detail.split()) # split the detail into words
                for word in detail.split(): # get a word from the detail
                    result = fz.get(word)    # get the matching
                    if(result and result[0][0]>=0.8 and not len(result[0][1])/2 < len(word)/2): #if the matching confidence is high and word length is high
                        matched_list.append((word, result))
                if abs(len(matched_list) - tokens_in_detail) < 1 and len(matched_list)!=0:
                    annot = (edu[0], 'ED', edu[2:])
                    logging.debug(annot)
                    self.tag_set.add(HashableTupleAnnotations(annot))
                else:
                    annot = (edu[0], 'NORG', edu[2:])
#                     logging.debug(annot)
                    self.neg_tag_set.add(HashableTupleAnnotations(annot))

        logging.debug('------NOUN CHUNCK MATCHING FOR EDUCATION------')
        for noun in self.spacy_noun_chunks:    #('Joachim Wilhelm Gauck', 0, 4)
            fz = fuzzyset.FuzzySet(use_levenshtein=False)
            for word in noun[0].split(): # add all the words into a fuzzy set from that sentence
                fz.add(word)
            for j, detail in enumerate(edu_names): # get a detail in the list under an info line
                matched_list = []
                tokens_in_detail = len(detail.split()) # split the detail into words
                for word in detail.split(): # get a word from the detail
                    result = fz.get(word)    # get the matching
                    if(result and result[0][0]>=0.9 and not len(result[0][1])/2 < len(word)/2): #if the matching confidence is high and word length is high
                        matched_list.append((word, result))
                if abs(len(matched_list) - tokens_in_detail) < 1 and len(matched_list)!=0:
                    logging.debug((noun[0], 'ED', noun[1:]))
                    self.tag_set.add(HashableTupleAnnotations((noun[0], 'ED', noun[1:])))
                # elif noun[0].split()[0] ==  detail.split()[0] and len(noun[0].split())>1: # lets add an exception for University name matching
                    # logging.debug((noun[0], 'ED', noun[1:]))
#                     self.tag_set.add(HashableTupleAnnotations((noun[0], 'ED', noun[1:])))
#                 else:
#                     self.neg_tag_set.add(HashableTupleAnnotations((noun[0], 'NED', noun[1:])))

    def _tag_children(self):
        logging.debug('------CHILDREN NAMES------')
        children_entities = []
        if not 'CHILDREN' in self.entity_dict:
            return
        children_names = [entity  for entity_list in self.entity_dict['CHILDREN'] for entity in entity_list['entity_list']]
        for entity in self.doc.ents:
            if entity.label_ == 'PERSON':
                children_entities.append((entity.text, entity.label_, entity.start, entity.end))

        for child in children_entities:
            fz = fuzzyset.FuzzySet(use_levenshtein=False)
            # for word in child[0].split(): # add all the words into a fuzzy set from that sentence
            #     fz.add(word)
            # for j, detail in enumerate(children_names): # get a detail in the list under an info line
            #     matched_list = []
            #     tokens_in_detail = len(detail.split()) # split the detail into words
            #     for word in detail.split(): # get a word from the detail
            #         result = fz.get(word)    # get the matching
            #         if(result and result[0][0]>=0.5 and not len(result[0][1])/2 < len(word)/2): #if the matching confidence is high and word length is high
            #             matched_list.append((word, result))
            #     if abs(len(matched_list) - tokens_in_detail) < 1 and len(matched_list)!=0:
            #         annot = (child[0], 'CH', child[2:])
            #         logging.debug(annot)
            #         self.tag_set.add(HashableTupleAnnotations(annot))
            fz.add(child[0])
            for j, detail in enumerate(children_names): # get a detail in the list under an info line(things coming from the side info box)
                result = fz.get(detail.split()[0])    # for a name, it should match the first name
                if(result and result[0][0]>=0.5 and not len(result[0][1])/2 < len(child[0])/2): #if the matching confidence is high and word length is high
                    annot = (child[0], 'CH', child[2:])
                    logging.debug(annot)
                    self.tag_set.add(HashableTupleAnnotations(annot))
                else:
                    annot = (child[0], 'NPE', child[2:])
#                     logging.debug(annot)
                    self.neg_tag_set.add(HashableTupleAnnotations(annot))
        logging.debug('------NOUN CHUNCK MATCHING CHILDREN------')
        for noun in self.spacy_noun_chunks:    #('Joachim Wilhelm Gauck', 0, 4)
            fz = fuzzyset.FuzzySet(use_levenshtein=False)
            for word in noun[0].split(): # add all the words into a fuzzy set from that sentence
                fz.add(word)
            for j, detail in enumerate(children_names): # get a detail in the list under an info line
                matched_list = []
                # tokens_in_detail = len(detail.split()) # split the detail into words
                # for word in detail.split(): # get a word from the detail
                #     result = fz.get(word)    # get the matching
                #     if result and result[0][0]>=0.5 and not len(result[0][1])/2 < len(word)/2 \
                #               and result[0][1][0] == word[0]: #if the matching confidence is high and word length is high
                #         matched_list.append((word, result))
                # if  len(matched_list)!=0:
                #     logging.debug((noun[0], 'CH', noun[1:]))
                #     self.tag_set.add(HashableTupleAnnotations((noun[0], 'CH', noun[1:])))
                for wn, word in enumerate(detail.split()): # get a word from the detail
                    result = fz.get(word)    # get the matching
                    if result and result[0][0]>=0.5 and not len(result[0][1])/2 < len(word)/2: #if the matching confidence is high and word length is high
                        matched_list.append((word, result))
                    elif wn == 0: #if the first word doesn't match, break the matching
                        break
                if  len(matched_list)!=0:
                    logging.debug((noun[0], 'CH', noun[1:]))
                    self.tag_set.add(HashableTupleAnnotations((noun[0], 'CH', noun[1:])))
#                 else:
#                     self.neg_tag_set.add(HashableTupleAnnotations((noun[0], 'NCH', noun[1:])))

    def _tag_parents(self):
        logging.debug('------PARENTS NAMES------')
        parent_entities = []
        if not 'PARENTS' in self.entity_dict:
            return
        parent_names = [entity  for entity_list in self.entity_dict['PARENTS'] for entity in entity_list['entity_list']]
        for entity in self.doc.ents:
            if entity.label_ == 'PERSON':
        #         print(entity.text, entity.label_, entity.start, entity.end)
                parent_entities.append((entity.text, entity.label_, entity.start, entity.end))
        logging.debug('------PERSON ENTITY MATCHING FOR PARENTS------')
        for parent in parent_entities:
            fz = fuzzyset.FuzzySet(use_levenshtein=False)
            for word in parent[0].split(): # add all the words into a fuzzy set from that sentence
                fz.add(word)
            for j, detail in enumerate(parent_names): # get a detail in the list under an info line
                matched_list = []
                tokens_in_detail = len(detail.split()) # split the detail into words
                for word in detail.split(): # get a word from the detail
                    result = fz.get(word)    # get the matching
                    if(result and result[0][0]>=0.5 and not len(result[0][1])/2 < len(word)/2): #if the matching confidence is high and word length is high
                        matched_list.append((word, result))
                if abs(len(matched_list) - tokens_in_detail) < 1 and len(matched_list)!=0:
                    annot = (parent[0], 'PR', parent[2:])
                    logging.debug(annot)
                    self.tag_set.add(HashableTupleAnnotations(annot))
                else:
                    annot = (parent[0], 'NPE', parent[2:])
#                     logging.debug(annot)
                    self.neg_tag_set.add(HashableTupleAnnotations(annot))
        logging.debug('------NOUN CHUNCK MATCHING FOR PARENTS------')
        for noun in self.spacy_noun_chunks:    #('Joachim Wilhelm Gauck', 0, 4)
            fz = fuzzyset.FuzzySet(use_levenshtein=False)
            noun_words = noun[0].split()
            for word in noun_words: # add all the words from the noun phrase into a fuzzy set
                fz.add(word)
            for j, detail in enumerate(parent_names): # get a one candidate
                matched_list = []
                tokens_in_detail = detail.split()
                if len(noun_words) < len(tokens_in_detail):
                    continue
                for i, word in enumerate(tokens_in_detail): # get a word from the detail
                    result = fz.get(word)    # get the matching
                    if result and result[0][0]>=0.5 and not len(result[0][1]) < len(word) \
                              and result[0][1][0] == word[0]: #if the matching confidence is high and word length is high
                        matched_list.append((word, result, i))
                # if  len(matched_list)!=0 and matched_list[0][2]==0: #and noun[0].split()[0][0] == detail.split()[0][0]:
                #     logging.debug((noun[0], 'PR', noun[1:]))
    #                 self.tag_set.add(HashableTupleAnnotations((noun[0], 'PR', noun[1:])))

"""# Tests"""

#experiment_code
# tagger = WikiConLLTagger('https://en.wikipedia.org/wiki/Barack_Obama')
# tagger = WikiConLLTagger('https://en.wikipedia.org/wiki/Donald_Trump')
tagger = WikiConLLTagger('https://en.wikipedia.org/wiki/Mahinda_Rajapaksa')

#experiment_code
logger.setLevel(logging.INFO)
df = pd.DataFrame(data = tagger.place_tags())
df.to_csv(r'conll_annot.csv', index = None, header=True)
print(tagger.tag_factory.entity_dict)
print(tagger.tag_factory.get_tag_summary())
print(df)

#experiment_code
fz = fuzzyset.FuzzySet(use_levenshtein=False)
# for word in spouse[0].split(): # add all the words into a fuzzy set from the entity
# fz.add('Shiranthi')
fz.add('Wickremasinghe')
fz.add('Shiranthi Wickremasinghe')

# for j, detail in enumerate(spouse_names): # get a detail in the list under an info line
#     matched_list = []
#     tokens_in_detail = len(detail.split()) # split the detail into words
#     for word in detail.split(): # get a word from the detail
#         result = fz.get(word)    # get the matching
#         if(result and result[0][0]>=0.5 and not len(result[0][1])/2 < len(word)/2): #if the matching confidence is high and word length is high
#             matched_list.append((word, result))

result = fz.get('Wickremasinghe')
result