# -*- coding: utf-8 -*-
"""mbert_ner_finetuning_poc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/196RKLhpux9gupXukOo3Rm4Y5pZcO1waz

# Fine Tune Modern BERT for Named Entity Recognition Task
### This notebook fine tunes modern BERT using the "bigcode/pii-dataset"  dataset for detecting Named entities and then recognize PII sensitive elements in the identified NER elements.
"""

!pip install --quiet transformers datasets seqeval torch
!pip install --quiet tf_keras
!pip install transformers[torch]

# pip install datasets
!pip install seqeval

import numpy as np
import torch
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForTokenClassification, AutoConfig
from transformers import Trainer, TrainingArguments
from seqeval.metrics import accuracy_score, f1_score, precision_score, recall_score

"""# ****************************************
# Configure the root of the Project Repo
# ****************************************
"""

debug=True
ROOTDIR ="/Users/pals/MICS/MIDS_266/project/privacy-ner-att"

MAX_SEQ_LENGTH = 128

conll_ds = load_dataset("conll2003", trust_remote_code=True)

' '.join(conll_ds['train'][4]['tokens'])

conll_ds['train']

ex=conll_ds['train'][4]
[x for x in zip(ex['tokens'], ex['ner_tags'],ex['pos_tags'],ex['chunk_tags'])]

ds_ele = conll_ds['train'][4]

if debug:
    print(ds_ele['tokens'], len(ds_ele['tokens']))
    print(ds_ele['pos_tags'], len(ds_ele['pos_tags']))
    print(ds_ele['chunk_tags'], len(ds_ele['chunk_tags']))
    print(ds_ele['ner_tags'], len(ds_ele['ner_tags']))

pos_tags   = conll_ds["train"].features["pos_tags"].feature.names
chunk_tags = conll_ds["train"].features["chunk_tags"].feature.names
ner_tags   = conll_ds["train"].features["ner_tags"].feature.names
if debug:
    print(pos_tags)
    print(chunk_tags)
    print(ner_tags)

pos_id2tag   = { k: v for k,v in enumerate(pos_tags)}
chunk_id2tag = { k: v for k,v in enumerate(chunk_tags)}
ner_id2tag   = { k: v for k,v in enumerate(ner_tags)}
if debug:
    print(ner_id2tag)

pos_tag2id   = { v: k for k,v in enumerate(pos_tags)}
chunk_tag2id = { v: k for k,v in enumerate(chunk_tags)}
ner_tag2id   = { v: k for k,v in enumerate(ner_tags)}
if debug:
    print(ner_tag2id)

def convert_ner_ids_to_label(ner_ids: list) -> list[str]:
    return [ner_id2tag[i] for i in ner_ids]

model_name = "answerdotai/ModernBERT-base"

mbert_tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_and_align_ner_tags(conll_ds: dict, tokenizer: object) -> None:
    input_tokens = tokenizer(conll_ds['tokens'],
                             truncation=True,
                             padding="max_length",  # Ensure fixed input size
                             max_length=MAX_SEQ_LENGTH,        # Set max token limit
                             is_split_into_words=True)
    input_labels = []
    for i, ner_tag_i in enumerate(conll_ds['ner_tags']):
        # For each ner_tag line associated with input sentence
        # get the tokenized word ids and then associated the
        # ner_label. Note: word_ids is not the actual tokens, rather it is
        # just word index corresponding to original input
        word_ids = input_tokens.word_ids(batch_index=i)
        aligned_ner_tag = []
        for word_id in word_ids:
            if word_id is None:
                aligned_ner_tag.append(-100)
            else:
                aligned_ner_tag.append(ner_tag_i[word_id])
        while len(aligned_ner_tag) < MAX_SEQ_LENGTH:
            aligned_ner_tag.append(-100)
        input_labels.append(aligned_ner_tag)
        if debug:
            if i == 0:
                print("input tokens ", i, conll_ds['tokens'][i])
                print("NER IDS      ", i, ner_tag_i)
                print("NER Labels   ", i, convert_ner_ids_to_label(ner_tag_i))
                print("Word Ids     ", i, input_tokens.word_ids(batch_index=i))
                print("Aligned NER  ", i, aligned_ner_tag)
    input_tokens['labels'] = input_labels
    return input_tokens

conll_ds = conll_ds.map(tokenize_and_align_ner_tags, batched=True, fn_kwargs={'tokenizer': mbert_tokenizer})
conll_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

"""# Prepare the MBert configuration for creating the Modern Bert Classifier task"""

mbert_config = AutoConfig.from_pretrained(
    model_name,
    num_labels = len(ner_tags),
    id2label = ner_id2tag,
    label2ids = ner_tag2id
)

mbert_model = AutoModelForTokenClassification.from_pretrained(
    model_name,
    config=mbert_config
)

device = torch.device("cpu")
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
print(f"Loading model to device: {device}")
mbert_model.to(device)

def compute_metrics(pred):
    logits, labels = pred

    # Convert logits to predicted class indices
    predictions = np.argmax(logits, axis=2)

    true_labels = []
    pred_labels = []

    for label_row, pred_row in zip(labels, predictions):  # Process each sentence
        temp_true = []
        temp_pred = []

        for label_id, pred_id in zip(label_row, pred_row):  # Process each token
            if label_id != -100:  # Ignore padding tokens
                temp_true.append(ner_id2tag[label_id])  # Convert true label to string
                temp_pred.append(ner_id2tag[pred_id])  # Convert predicted label to string

        if temp_true:  # Only add non-empty sequences
            true_labels.append(temp_true)
            pred_labels.append(temp_pred)

    return {
        "accuracy": accuracy_score(true_labels, pred_labels),
        "f1": f1_score(true_labels, pred_labels),
        "precision": precision_score(true_labels, pred_labels),
        "recall": recall_score(true_labels, pred_labels),
    }

MODEL   = "mbert"
OUTDIR  = f"{ROOTDIR}/build/{MODEL}/results"
LOGDIR  = f"{ROOTDIR}/build/{MODEL}/logs"
BATCH_SIZE = 8
NUM_EPOCHS = 10
WT_DECAY = 0.01

# Training arguments
training_args = TrainingArguments(
    output_dir=OUTDIR,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    weight_decay=WT_DECAY,
    logging_dir=LOGDIR
)

# Initialize Trainer
trainer = Trainer(
    model=mbert_model,
    args=training_args,
    train_dataset=conll_ds["train"],
    eval_dataset=conll_ds["validation"],
    compute_metrics=compute_metrics
)

trainer.train()

def predict_ner(text, tokenizer, model):
    tokens = tokenizer(text, return_tensors="pt", truncation=True)
    device = torch.device("mps")
    print(f"Loading model to device: {device}")
    model.to(device)
    model.eval()
    tokens = {key: value.to(device) for key, value in tokens.items()}
    with torch.no_grad():
        outputs = model(**tokens)

    predictions = torch.argmax(outputs.logits, dim=2)
    predicted_labels = [ner_id2tag[id.item()] for id in predictions[0]]

    return list(zip(tokenizer.tokenize(text), predicted_labels))

# Test with a news sentence
text = "Kennedy delivered his famous speech at Rice University."
print(predict_ner(text, mbert_tokenizer, mbert_model))

{'O': 0, 'B-PER': 1, 'I-PER': 2, 'B-ORG': 3, 'I-ORG': 4, 'B-LOC': 5, 'I-LOC': 6, 'B-MISC': 7, 'I-MISC': 8}

# POS - Tag	Description	Example
  # CC	Coordinating conjunction	and, but, or
  # CD	Cardinal number	one, two, 3.14
  # DT	Determiner	the, a, an
  # EX	Existential there	there is
  # FW	Foreign word	voilà, et cetera
  # IN	Preposition/Subordinating conjunction	in, of, like
  # JJ	Adjective	big, green, fast
  # JJR	Adjective, comparative	bigger, faster
  # JJS	Adjective, superlative	biggest, fastest
  # LS	List item marker	1., a., i.
  # MD	Modal	can, will, must
  # NN	Noun, singular or mass	cat, book, laptop
  # NNS	Noun, plural	cats, books
  # NNP	Proper noun, singular	John, NASA
  # NNPS	Proper noun, plural	Rockies, Beatles
  # PDT	Predeterminer	all, both, many
  # POS	Possessive ending	’s, ’
  # PRP	Personal pronoun	I, you, he, she
  # PRP$	Possessive pronoun	my, your, their
  # RB	Adverb	quickly, very
  # RBR	Adverb, comparative	faster, better
  # RBS	Adverb, superlative	fastest, best
  # RP	Particle	up, off, out
  # SYM	Symbol	%, $, @, &, +
  # TO	"to"	to go, to eat
  # UH	Interjection	wow, oh, ah
  # VB	Verb, base form	go, eat, run
  # VBD	Verb, past tense	went, ate, ran
  # VBG	Verb, gerund/present participle	going, eating
  # VBN	Verb, past participle	gone, eaten
  # VBP	Verb, non-3rd person singular present	go, eat
  # VBZ	Verb, 3rd person singular present	goes, eats
  # WDT	Wh-determiner	which, that
  # WP	Wh-pronoun	who, what
  # WP$	Possessive wh-pronoun	whose
  # WRB	Wh-adverb	where, when

# Syntactic Chunk Tags
  # NP (Noun Phrase)	Group of words functioning as a noun	"The big dog"
  # VP (Verb Phrase)	A verb with its objects or modifiers	"is running quickly"
  # PP (Prepositional Phrase)	Preposition + noun phrase	"on the table"
  # ADJP (Adjective Phrase)	Group of adjectives modifying a noun	"extremely happy"
  # ADVP (Adverb Phrase)	Group of adverbs modifying a verb/adjective	"very quickly"
  # SBAR (Subordinate Clause)	Clause introduced by subordinating conjunction	"because he was tired"

